POST http://localhost:9000/member/api/register
Content-Type: application/json

{
  "mobile": 18660182913
}

###

POST http://localhost:9000/member/api/verification/send
Content-Type: application/json

{
  "mobile": 18660182913
}

###

POST http://localhost:9000/member/api/login
Content-Type: application/json

{
  "mobile": 18660182913,
  "code": 8888
}

###

GET http://localhost:9000/member/api/hello
Content-Type: application/json
